[package]
name = "two_way_map"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.22.0", features = ["derive"] }

[lints.rust]
warnings = "forbid"
unsafe-code = "forbid"

[lints.clippy]
all = "deny"
